### ISSUE TITLE
Real World match testing appears to have already occured - (Danish Radio show) (Probably not with this project)

### ISSUE THREAD

**Issue by kuseler** [RonSijm/ButtFish#10]
[source](https://www.reddit.com/r/chess/comments/xr3ft2/gm_jonas_bjerre_plays_against_journalist_that/?utm_source=share&utm_medium=ios_app&utm_name=iossmf)

Edit: although with a cock ring, it appears to be sufficient evidence for the concept

**Comment by RonSijm** [comment]
Thanks. I was aware, yes. Technically my project compatible with Cock rings, as they're also [part of the supported devices by Buttplug.io](https://iostindex.com/?filter0Availability=Available,DIY&filter1Connection=Digital)

Buttplug.io tweeted about it, https://t.co/nGaL405ToW and I left a reply with more details.

Apparently they're a Danish radio station, and their episode about it can be found here: https://www.dr.dk/lyd/p3/pastand-mod-pastand/pastand-mod-pastand-2022-09-28

In the post they mention it didn't really work due to so miscommunication issues. 

On discord @qdot (Buttplug.io core dev) speculated: It’d be cool if they used the project but I’m going to guess this is literally someone sitting there with a stock toy control app just hitting the button manually.

If there are any Danish speakers out there, maybe someone can reach out to them so we can assist them testing it with this project

**Comment by RonSijm** [comment]
not an issue - could be moved to discussions if other people want to discuss this
