### ISSUE TITLE
The translation from chinese to english in readme image may get better

### ISSUE THREAD

**Issue by edimetia3d** [RonSijm/ButtFish#15]
Hi,

It's this one, there might be some joke that only native speakers could get.
![img](https://user-images.githubusercontent.com/337928/193144038-f80dddbb-afd9-40ab-86db-7bff14a20494.png)

The word "炼肛大师" obviously comes from the "钢之炼金术师", i.e. "Fullmetal Alchemist" in english
So I guess it might be funnier to translate to "FullAnal Alchemist" instead of "Anal Master"

XD

**Comment by RonSijm** [comment]
Thanks - I appreciate the better translation from someone that actually speaks Chinese. "FullAnal Alchemist" would be the correct translation then?

The initial translation is one directly from google translate. 

The picture of the Stickman is indicate being somewhat opposed to randomly getting the title "Anal Master" 😂 - I didn't know this was a joke that didn't translate very well. Not sure if I can fix it with _FullAnal Alchemist_, since with a title like that they're clearly not being serious
