### ISSUE TITLE
Improper use of Venn diagram makes it unclear whether author is "the chosen one" 

### ISSUE THREAD

**Issue by therealdaniel** [RonSijm/ButtFish#7]
In the Venn diagram in readme.md, it appears that "ME" is a symbol representing the entire "People who can program" category (in the same way the Knight and butt icons are representative of people who can play chess, and people who are into buttstuff respectively). The overlap of this category with the other two categories implies that the author is also into butstuff and can play chess, thereby making them the chosen one.

![Venn Diagram](https://user-images.githubusercontent.com/32955646/192938987-8b921555-5d59-49fe-8f98-4fa816222382.png)

However this is contradictory with the text that follows, saying that the chosen one is as yet to found.

A Venn diagram has circles representing groups within a population and describes how individuals in the population can be in multiple groups.  "ME" is an individual, whereas "people who can program" is a group of people. 

If the author intended to suggest that they can program, but are _not_ into buttstuff, nor can they play chess, then "ME" needs to be moved from being a title of the category, to a data point within the category. eg:

![image](https://user-images.githubusercontent.com/32955646/192942674-e81d41f5-bc05-4edb-b36d-d62454463055.png)

**Comment by RonSijm** [comment]
Hey, thanks for the suggestion, I was aware that the Venn diagram was somewhat confusing. 

Part of the joke is that the ME part of the Venn diagram only overlaps the "People who can program" about 33% - Implying I can program, but barely.

It's a bit confusing because of the iconization of the other two circles... I saw this Venn Diagram design somewhere (with icons) - and I liked it way more than plan old Venn diagrams without icons.

I'm not sure if there's a way to keep iconization and also the joke of my bubble only overlapping the programming part by small proportion

**Comment by RonSijm** [comment]
Don't see a good way to change this right now, nor are there any suggestions incoming in this issue. 

Plus the diagram has been covered by a bunch of media, including Hikaru. Don't know if changing it now is the best idea
